### ISSUE TITLE
[BUG REPORT]: Query String on Local File Not Working

### ISSUE THREAD

**Issue by i-vone** [1Danish-00/HtmlWebShot#1]
### Your System?

Windows 10

### Version

3.8

### Version

latest

### What happened?

When I try to take a screenshot of a local file whilst providing a URL query string, it does not work. My assumption is that it tried to look for a file which contains the query string in the filename.

### Paste Your Codes.

```python
shot.create_pic(html=r"folder\file.html?username=hi", css=r"folder\tweet.css", output="output.jpg")
```

### Your Error Logs.

```shell
It does not output an error
```

**Comment by 1Danish-00** [comment]
> ### Your System?
> Windows 10
> 
> ### Version
> 3.8
> 
> ### Version
> latest
> 
> ### What happened?
> When I try to take a screenshot of a local file whilst providing a URL query string, it does not work. My assumption is that it tried to look for a file which contains the query string in the filename.
> 
> ### Paste Your Codes.
> ```python
> shot.create_pic(html=r"folder\file.html?username=hi", css=r"folder\tweet.css", output="output.jpg")
> ```
> 
> ### Your Error Logs.
> ```shell
> It does not output an error
> ```

Have u installed [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html) for windows?


And set [path Configuration](https://github.com/1Danish-00/HtmlWebShot#config-path)?

And you have to put exact file path or html string for it to work.

and its not giving error log 🤔, that's an issue i'll check it.

**Comment by i-vone** [comment]
Yes, I have. It works on local files (and also online webpages) when I don't provide a query string...

**Comment by 1Danish-00** [comment]
> Yes, I have. It works on local files (and also online webpages) when I don't provide a query string...

well then yes , it won't work on query string 😅
